'use strict';
const KEY='vectra3d-graduation-2026-v1';
const RECOVERY_KEY=KEY+'-before-restore';
let lastSavedRaw=null;
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const today=localDate();
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const statuses=['Not started','In progress','Blocked','Done'];
let state=clone(SEED),storageOK=true,restoreCandidate=null,initialWarning='';
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s+'T12:00:00'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
const textOK=(s,n=12000)=>typeof s==='string'&&s.length<=n;
function validate(x){
 if(!x||x.schema!==1)throw Error('This is not a version 1 Vectra3D dashboard backup.');
 for(const key of ['tasks','deliverables','research','risks']){
  if(!Array.isArray(x[key])||x[key].length!==SEED[key].length)throw Error('The backup has an incompatible '+key+' list.');
  const ids=x[key].map(i=>i.id);if(new Set(ids).size!==ids.length||SEED[key].some(i=>!ids.includes(i.id)))throw Error('The backup has invalid '+key+' IDs.');
 }
 const clean=clone(SEED);
 clean.tasks.forEach(i=>{const v=x.tasks.find(t=>t.id===i.id);if(!statuses.includes(v.status)||!validDate(v.due))throw Error('Invalid task status or date.');i.status=v.status;i.due=v.due;});
 clean.deliverables.forEach(i=>{const v=x.deliverables.find(t=>t.id===i.id);if(!['Not started','Draft','In review','Ready'].includes(v.status)||!textOK(v.evidence,2000))throw Error('Invalid deliverable entry.');i.status=v.status;i.evidence=v.evidence;});
 clean.research.forEach(i=>{const v=x.research.find(t=>t.id===i.id);for(const k of ['confirmed','completed']){if(!Number.isInteger(v[k])||v[k]<0||v[k]>10000)throw Error('Invalid research count.');i[k]=v[k];}});
 clean.risks.forEach(i=>{const v=x.risks.find(t=>t.id===i.id);if(!['Open','Monitoring','Resolved'].includes(v.status))throw Error('Invalid risk status.');i.status=v.status;});
 if(!Array.isArray(x.logs)||x.logs.length>20000||!textOK(x.review,50000))throw Error('Invalid notes or activity log.');
 const logIds=new Set();
 clean.logs=x.logs.map(l=>{if(!textOK(l.id,100)||logIds.has(l.id)||!validDate(l.date)||!['Graduation','Business','Supervision','Decision','Expense'].includes(l.type)||!textOK(l.note,1500)||typeof l.value!=='number'||!Number.isFinite(l.value)||l.value<0||l.value>100000||(['Graduation','Business'].includes(l.type)&&l.value>24))throw Error('Invalid activity entry.');logIds.add(l.id);return {id:l.id,date:l.date,type:l.type,note:l.note,value:l.value};});
 clean.review=x.review;clean.lastBackup=typeof x.lastBackup==='string'?x.lastBackup:null;return clean;
}
try{const saved=localStorage.getItem(KEY);lastSavedRaw=saved;if(saved)state=validate(JSON.parse(saved));}catch(e){storageOK=false;initialWarning='Saved data could not be loaded. It has not been overwritten. Export or restore a valid backup. '+e.message;}
function toast(s){const n=document.querySelector('#notice');n.textContent=s;n.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>n.style.display='none',6500);}
function storageWarning(message){
 const banner=document.querySelector('#storage-warning');banner.hidden=false;
 banner.querySelector('span').textContent=message;
 document.querySelector('#save-state').textContent='Not saved · export before reloading';
}
function save(){try{
 if(!storageOK)throw Error('Your edits are only in this tab. Export them before reloading or restoring.');
 if(localStorage.getItem(KEY)!==lastSavedRaw){storageOK=false;throw Error('Another tab changed or cleared the saved dashboard. Export your edits before reloading; automatic saving is paused.');}
 const raw=JSON.stringify(state);localStorage.setItem(KEY,raw);lastSavedRaw=raw;
 document.querySelector('#storage-warning').hidden=true;
 document.querySelector('#save-state').textContent='Saved in this browser';return true;
 }catch(e){storageWarning(e.message);toast(e.message);return false;}}
function select(options,value,attrs=''){return `<select ${attrs}>${options.map(x=>`<option${x===value?' selected':''}>${esc(x)}</option>`).join('')}</select>`;}
function source(ref){const isAgreement=ref.startsWith('Agreement');const page=(ref.match(/p{1,2}\.\s*(\d+)/)||[])[1]||1;return `<a href="sources/${isAgreement?'Agreement':'Proposal'}.pdf#page=${page}" target="_blank" rel="noopener">${esc(ref)}</a>`;}
function currentWeek(){return state.weeks.find(w=>today>=w.start&&today<=addDays(w.end,2));}
function addDays(d,n){const date=new Date(d+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);}
function weekNumber(){return currentWeek()?.n||state.weeks.find(w=>w.start>today)?.n||19;}
function holiday(){return today>='2026-10-26'&&today<='2026-11-01'?'Autumn buffer week':today>='2026-12-21'&&today<='2027-01-03'?'Christmas break':null;}
function head(title,desc){return `<div class="heading"><div><h1>${title}</h1><p class="lead">${desc}</p></div><div class="date">${new Date(today+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div></div>`;}
function taskRow(t){return `<tr class="${t.status==='Done'?'completed':''}"><td><span class="task-title">${esc(t.title)}</span><details><summary>${esc(t.id)} · Details & source</summary><p>${esc(t.detail||'Follow the student-owned activities in the proposal.')}</p><p>${source(t.source)}</p><label>Due date (editable; confirm with tutor)<input type="date" value="${t.due}" data-date="${t.id}" aria-label="Due date for ${esc(t.title)}"></label></details></td><td class="num">W${t.week}<p>${t.kind}</p></td><td class="num">${fmt(t.due)}${t.due<today&&t.status!=='Done'?'<p class="danger">Past plan date · verify</p>':''}</td><td>${select(statuses,t.status,`data-task="${t.id}" aria-label="Status for ${esc(t.title)}"`)}</td></tr>`;}
function tasksTable(tasks){return tasks.length?`<div class="table-wrap"><table><thead><tr><th scope="col">Action</th><th scope="col">Week</th><th scope="col">Planned due</th><th scope="col">Status</th></tr></thead><tbody>${tasks.map(taskRow).join('')}</tbody></table></div>`:'<div class="panel empty">No tasks match these filters. Try all weeks or another status.</div>';}
function totals(){const w=currentWeek();const weekStart=w?.start||addDays(today,-((new Date(today+'T12:00:00').getDay()+6)%7));const entries=state.logs.filter(l=>l.date>=weekStart&&l.date<=addDays(weekStart,6));return {grad:entries.filter(l=>l.type==='Graduation').reduce((s,l)=>s+l.value,0),business:entries.filter(l=>l.type==='Business').reduce((s,l)=>s+l.value,0)};}
function hoursLine(){const h=totals();return `<div class="stat-line"><div><strong>${h.grad.toFixed(1)} / ${holiday()?'writing only':'40'} h</strong><br><span>Graduation this week</span></div><div><strong>${h.business.toFixed(1)} / 4 h</strong><br><span>Commercial, separate</span></div></div>${h.business>4?'<p class="hours-warning">Commercial hours exceed the proposal’s weekly cap.</p>':''}${holiday()?'<p class="small">No participant sessions during breaks. Christmas: at most 30% of the period, writing only.</p>':''}`;}
const milestoneTasks=['T08','T12','T16','T21',null,'T26','T28',null,'T31','T35',null,null,'T38'];
function currentMilestones(){return state.milestones.map((m,index)=>{
 const task=state.tasks.find(t=>t.id===milestoneTasks[index]);
 const date=task?task.due:m.date;
 return {...m,index,date,originalDate:m.date,changed:date!==m.date,taskId:task?.id};
 }).sort((a,b)=>a.date.localeCompare(b.date));}
function scheduleTable(){return `<h2>Milestones and deadlines</h2><p class="small">Linked task edits appear here and in calendar exports. Original source dates remain visible. Review weeks and the agreement end date remain baseline references.</p><div class="table-wrap"><table><thead><tr><th>Milestone</th><th>Current date</th><th>Source / status</th></tr></thead><tbody>${currentMilestones().map(m=>`<tr><td><strong>${esc(m.title)}</strong>${m.taskId?`<p>Linked to ${m.taskId} · edit in Tasks</p>`:''}</td><td class="num">${fmt(m.date)}${m.changed?`<p>Source: ${fmt(m.originalDate)}</p>`:''}</td><td><span class="tag ${m.changed||m.type==='Provisional'?'warn':''}">${m.changed?'Edited · confirm':m.type}</span><p>${source(m.source)}</p></td></tr>`).join('')}</tbody></table></div>`;}
function evidenceSummary(){const ready=state.deliverables.filter(d=>d.status==='Ready');const missing=ready.filter(d=>!d.evidence.trim());return `${ready.length} of 12 marked ready · ${missing.length} ready without an evidence reference`;}
function reviewChecks(){const missing=state.deliverables.filter(d=>d.status==='Ready'&&!d.evidence.trim()).length;const overdue=state.tasks.filter(t=>t.due<today&&t.status!=='Done').length;const blocked=state.tasks.filter(t=>t.status==='Blocked').length;return `<div class="attention"><strong>Review before closing the week:</strong> ${overdue} past-date tasks to verify · ${blocked} blocked tasks · ${missing} ready deliverables without evidence. <a href="#tasks">Review tasks</a> · <a href="#deliverables">Review evidence</a></div>`;}
function overview(){const w=state.weeks[weekNumber()-1];const open=state.tasks.filter(t=>t.status!=='Done').sort((a,b)=>a.due.localeCompare(b.due));const next=currentMilestones().filter(m=>m.date>=today).slice(0,4);const done=state.tasks.filter(t=>t.status==='Done').length;const inPeriod=today>='2026-08-31'&&today<='2027-01-29';return head('A clearer path to graduation.','The choice phase of small-scale Dutch housing projects. Your next actions, evidence and decisions in one place.')+
`<section class="week-strip"><div class="week-index"><small>${holiday()?'BREAK':inPeriod?'WEEK':'PLAN'}</small>${holiday()?'—':w.n.toString().padStart(2,'0')}</div><div><h2>${holiday()||(!inPeriod?'Project plan · '+w.title:w.title)}</h2><p>${holiday()?'Protect the break. Use the plan to prepare independent writing and the next working week.':esc(w.detail)}</p></div><button data-week-open="${w.n}">Open week ${w.n} tasks</button></section>
<div class="attention"><strong>Confirm before relying on the plan.</strong> Assessment dates await calendar verification; formal THUAS approval is unverified. <a href="#risks">Review open points</a></div>
<div class="columns"><section class="panel"><div class="panel-title"><h2>Next actions</h2><a href="#tasks">All ${state.tasks.length} tasks</a></div>${open.slice(0,5).map(t=>`<div class="item"><div class="item-title">${esc(t.title)}</div><p>${esc(t.detail)}</p><div class="meta">Week ${t.week} · ${fmt(t.due)} · <span class="tag ${t.due<today?'warn':''}">${t.due<today?'Past plan date · verify':t.status}</span></div></div>`).join('')||'<p>All planned tasks are marked done. Check evidence and submission records.</p>'}<div class="status-line"><meter value="${done}" max="${state.tasks.length}" aria-label="Tasks marked done"></meter><span class="small">${done} of ${state.tasks.length} marked done</span></div></section>
<div><section class="panel"><h2>Coming up</h2>${next.map(m=>`<div class="item"><div class="meta">${fmt(m.date)}</div><div class="item-title">${esc(m.title)}</div><p><span class="tag ${m.changed||m.type==='Provisional'?'warn':''}">${m.changed?'Edited · confirm':m.type}</span></p></div>`).join('')||'<p>No future milestones in the baseline plan.</p>'}<a href="#timeline">View the full timeline</a></section><section class="panel"><h2>Make room for the work</h2>${hoursLine()}<a href="#logs">Log hours or a supervision note</a></section></div></div>`;}
let taskFilter={week:'all',status:'open',search:''};
function filteredTasks(){return state.tasks.filter(t=>(taskFilter.week==='all'||t.week===Number(taskFilter.week))&&(taskFilter.status==='all'||(taskFilter.status==='open'?t.status!=='Done':t.status===taskFilter.status))&&(`${t.title} ${t.detail} ${t.id}`.toLowerCase().includes(taskFilter.search.toLowerCase())));}
function tasksView(){return head('Tasks','Update actual progress. Dates come from the proposal; changes here do not amend the source documents.')+`<div class="toolbar"><label class="search">Find a task<input id="task-search" type="search" placeholder="Search tasks or IDs" value="${esc(taskFilter.search)}"></label><label>Working week<select id="task-week"><option value="all">All weeks</option>${state.weeks.map(w=>`<option value="${w.n}"${String(w.n)===taskFilter.week?' selected':''}>Week ${w.n}</option>`).join('')}</select></label><label>Show<select id="task-status">${[['open','Open tasks'],['all','All statuses'],...statuses.map(x=>[x,x])].map(([v,l])=>`<option value="${v}"${taskFilter.status===v?' selected':''}>${l}</option>`).join('')}</select></label></div><div id="task-results">${tasksTable(filteredTasks())}</div>`;}
function timeline(){let rows='';for(const w of state.weeks){rows+=`<div class="week-row ${currentWeek()?.n===w.n?'current':''}"><div class="week-number">${String(w.n).padStart(2,'0')}</div><div class="date">${fmt(w.start)}<br>to ${fmt(w.end)}<p><span class="tag">${w.phase}</span></p></div><div><h3>${esc(w.title)}</h3><p>${esc(w.detail)}</p><button class="small-button" data-week-open="${w.n}">Week ${w.n} tasks</button></div></div>`;if(w.n===8||w.n===15)rows+=`<div class="week-row break"><div>—</div><div class="date">${w.n===8?'26–30 Oct 2026':'21 Dec – 1 Jan'}</div><div><h3>${w.n===8?'Autumn buffer':'Christmas break'}</h3><p>No participant sessions. ${w.n===8?'Midterm materials still provisionally due 29 October.':'At most 30% of the period used for independent writing.'}</p></div></div>`;}return head('19 working weeks','Two diamonds, two test rounds. The dated table is followed; holiday weeks are not counted as working weeks.')+`<div class="attention">Assessment dates are <strong>provisional</strong>. The agreement fixes the project period. Exact review meeting days still need confirmation.</div><div class="actions" style="margin:0 0 20px"><button id="calendar">Export current calendar (.ics)</button><a href="sources/Proposal.pdf#page=5" target="_blank" rel="noopener">Read source planning</a></div><section class="panel">${scheduleTable()}</section><div class="list-surface">${rows}</div>`;}
function deliverables(){return head('Deliverables','Twelve outputs, tied to the assessment criteria. Add file references so every status has traceable evidence.')+`<p class="attention" id="evidence-summary">${evidenceSummary()}</p><div class="list-surface">${state.deliverables.map(d=>`<article class="deliverable"><div><h3><span>${d.id}</span>${esc(d.title)}</h3><p>${esc(d.detail)}</p><span class="tag">${esc(d.criteria)}</span><p>Folder: <code>${d.folder}</code> · ${source(d.source)}</p></div><div><label>Status${select(['Not started','Draft','In review','Ready'],d.status,`data-deliverable="${d.id}" aria-label="Status for ${esc(d.title)}"`)}</label><label>Evidence file reference<input data-evidence="${d.id}" value="${esc(d.evidence)}" maxlength="2000" placeholder="File name, version and review reference"></label></div></article>`).join('')}</div>`;}
function research(){return head('Research planning','Scheduling and aggregate counts from the proposal. No names, recordings, transcripts, participant choices or findings belong here.')+`<div class="attention">Counts start at zero because no actual progress was supplied. Student-led research, coding, synthesis and design remain outside this dashboard.</div><div class="table-wrap"><table><thead><tr><th>Activity</th><th>Target / timing</th><th>Confirmed</th><th>Completed</th></tr></thead><tbody>${state.research.map(r=>`<tr><td><strong>${r.title}</strong><p>${r.questions}</p></td><td>${r.target}<p>${r.timing}</p></td><td><input class="study-count" type="number" min="0" max="10000" step="1" value="${r.confirmed}" data-study="${r.id}" data-field="confirmed" aria-label="Confirmed count for ${r.title}"></td><td><input class="study-count" type="number" min="0" max="10000" step="1" value="${r.completed}" data-study="${r.id}" data-field="completed" aria-label="Completed count for ${r.title}"></td></tr>`).join('')}</tbody></table></div><section class="panel" style="margin-top:24px"><h2>Evaluation reference · both iterations</h2><ul class="checklist"><li><strong>Comprehension:</strong> 80% can correctly name 4 of 5 consequences.</li><li><strong>Confidence:</strong> before/after on a 5-point scale; target increase of at least 1 point.</li><li><strong>Stuck moments:</strong> fewer in iteration 2 than iteration 1.</li><li><strong>Defensibility:</strong> follow up one week later; reasoning matches the decision-day record.</li><li><strong>Session length:</strong> within the planned duration without cutting comparison short.</li><li><strong>Professional fit:</strong> three professionals judge fit without avoidable work.</li></ul><p class="small">These are proposal targets, not results. Raw measures and analysis stay in approved research storage. ${source('Proposal pp.16–17')}</p></section>`;}
function logs(){return head('Hours & supervision','Track graduation and commercial time separately. Keep notes administrative and record the next confirmed sponsor meeting.')+`<div class="columns"><section class="panel"><h2>Add an entry</h2><form id="log-form"><div class="form-grid"><label>Date<input name="date" type="date" value="${today}" required></label><label>Entry type<select name="type" id="log-type"><option>Graduation</option><option>Business</option><option>Supervision</option><option>Decision</option><option>Expense</option></select></label><label id="value-label">Hours<input name="value" id="log-value" type="number" min="0.25" max="24" step="0.25" required></label><label class="full">Administrative note / reference<textarea name="note" maxlength="1500" required placeholder="Task ID, meeting action or receipt reference. No participant data."></textarea></label></div><button class="primary" type="submit">Save entry</button></form></section><section class="panel"><h2>Weekly capacity</h2>${hoursLine()}<p class="small">Sponsor: Ronald Visser · 30 minutes every two weeks.<br>Tutor: Robbert Gerretsen · Partner: Rik van Wieren.<br>Record the first agreed meeting date; recurring meetings are not assumed.</p><p>${source('Agreement p.2 §3')}</p></section></div><section class="panel"><h2>Activity log</h2>${state.logs.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Reference / action</th><th>Manage</th></tr></thead><tbody>${[...state.logs].sort((a,b)=>b.date.localeCompare(a.date)).map(l=>`<tr><td class="num">${fmt(l.date)}</td><td>${l.type}</td><td class="num">${['Graduation','Business'].includes(l.type)?l.value+' h':l.type==='Expense'?'€ '+l.value.toFixed(2):'—'}</td><td>${esc(l.note)}</td><td><button class="small-button" data-delete="${esc(l.id)}" aria-label="Remove ${esc(l.type)} entry on ${l.date}">Remove</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="small">No entries yet. Log today’s work or your next confirmed supervision action.</p>'}</section>`;}
function risks(){return head('Gates & risks','Source-based triggers and unresolved administrative checks. Mark resolved only when you have evidence.')+`<div class="table-wrap"><table><thead><tr><th>Issue / response</th><th>Check when</th><th>Status</th></tr></thead><tbody>${state.risks.map(r=>`<tr><td><strong>${r.title}</strong><p>${r.response}</p><p>${source(r.source)}</p></td><td>${r.trigger}</td><td>${select(['Open','Monitoring','Resolved'],r.status,`data-risk="${r.id}" aria-label="Status for ${r.title}"`)}</td></tr>`).join('')}</tbody></table></div><p class="small">Publication: confirm the unfilled timing alternatives in agreement §6.2; record company receipt/review before release. Final-report retention is separate from raw-data retention.</p>`;}
function review(){return head('Weekly review','Close the week with evidence, a realistic next step and a recoverable backup.')+reviewChecks()+`<div class="columns"><section class="panel"><h2>Your review notes</h2><label for="review-notes">Administrative summary only</label><textarea id="review-notes" maxlength="50000" placeholder="Week / completed task IDs / evidence file references / next 3 priorities / blockers / tutor or sponsor decisions / confirmed next meeting">${esc(state.review)}</textarea><p class="small">Notes save as you type. Export a weekly snapshot to preserve older reviews.</p><div class="actions"><button id="review-export" class="primary">Export weekly review</button><button id="print-review">Print this view</button></div></section><section class="panel"><h2>Friday close-out</h2><ol class="checklist"><li>Update tasks and deliverable file references.</li><li>Check recruitment thresholds and permissions.</li><li>Review 40 graduation hours and the separate 4-hour business cap.</li><li>Prepare the fortnightly sponsor conversation.</li><li>Choose three priorities for next week.</li><li>Export a JSON backup and keep prior versions.</li></ol><p class="small">Last backup download initiated: ${state.lastBackup?esc(new Date(state.lastBackup).toLocaleString('en-GB')):'Not yet'}. Check your browser’s download location.</p><div class="export-row"><button id="backup-inline">Export backup</button><button id="restore">Restore backup</button><button id="recovery-export">Export pre-restore copy</button></div></section></div>`;}
function library(){return head('Files & guidance','The supplied PDFs are the source baseline. Existing documents were left in place; this folder holds the new working environment.')+`<div class="columns"><section class="panel"><h2>Source documents</h2><ul class="file-list"><li><a href="sources/Proposal.pdf" target="_blank" rel="noopener"><strong>Vectra3D Graduation Proposal 2.0</strong></a><p>18 pages · planning, deliverables, research plan and risks.</p></li><li><a href="sources/Agreement.pdf" target="_blank" rel="noopener"><strong>Graduation assignment agreement</strong></a><p>6 pages · period, supervision, approval and handling of project material.</p></li></ul><h2 style="margin-top:28px">Working folders</h2><ul class="file-list">${[['00_Project_control','Requirements, source hashes and open points'],['01_Research_admin','Scheduling and administrative registers'],['02_Student_research','Student-authored work; confirm access-controlled storage first'],['03_Design_brief / 04_Concept_development','Student-owned design work'],['05_Prototype_tests / 06_Final_service','Iteration artifacts and final service'],['07_Reports / 08_Presentation_webpage','Reports and communication deliverables'],['09_Business / 10_Submission_archive','Separate business records and frozen submission'],['Templates / Backups','Blank records and exported dashboard snapshots']].map(([a,b])=>`<li><strong>${a}</strong><p>${b}</p></li>`).join('')}</ul><p class="small">Open the Graduation_Workspace folder in File Explorer to use these files. The browser cannot move or manage them.</p></section><div><section class="panel"><h2>Use the right skill</h2><ul class="file-list"><li><strong>PDF / Documents</strong><p>Format and check student-authored reports.</p></li><li><strong>Presentations</strong><p>Prepare permitted presentation material.</p></li><li><strong>Impeccable</strong><p>Dashboard and public webpage usability, responsive layout and accessibility.</p></li><li><strong>Spreadsheets</strong><p>Administrative hours, expenses and planning.</p></li></ul><p class="small">Research-analysis and concept-generation skills fall outside the proposal’s stated AI boundary unless an approved change allows them. Declare assistance in the AI-use register.</p></section><section class="panel"><h2>Storage & recovery</h2><p class="small">Saved entries live in this browser, not in the HTML files. Keep the same browser and address. Export before clearing browser data or moving the dashboard. No sync or encryption is provided by this tool.</p><div class="actions"><button id="backup-inline">Export backup</button><button id="restore">Restore backup</button><button id="recovery-export">Export pre-restore copy</button></div></section></div></div>`;}
const pages={overview,tasks:tasksView,timeline,deliverables,research,logs,risks,review,library};
function render(){const route=location.hash.slice(1)||'overview';document.querySelector('#main').innerHTML=(pages[route]||overview)();document.querySelectorAll('nav a').forEach(a=>{a.removeAttribute('aria-current');if(a.hash==='#'+(pages[route]?route:'overview'))a.setAttribute('aria-current','page');});document.title='Vectra3D · '+({overview:'This week',tasks:'Tasks',timeline:'19-week plan',deliverables:'Deliverables',research:'Research planning',logs:'Hours & supervision',risks:'Gates & risks',review:'Weekly review',library:'Files & guidance'}[route]||'Graduation');}
function download(name,body,type){const blob=new Blob([body],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function backup(){state.lastBackup=new Date().toISOString();download('Vectra3D-backup-'+today+'-'+Date.now()+'.json',JSON.stringify(state,null,2),'application/json');save();toast('Backup download started. Save it in your approved backup location.');}
function exportReview(){const h=totals();download('Vectra3D-weekly-review-'+today+'.md',`# Vectra3D weekly review — ${today}\n\n${state.review||'No review notes entered.'}\n\n## Recorded weekly hours\nGraduation: ${h.grad}; Business: ${h.business}.\n\n## Task status\n${state.tasks.map(t=>`- ${t.id} [${t.status}] ${t.title} — ${t.due}`).join('\n')}\n\n## Deliverable evidence\n${state.deliverables.map(d=>`- ${d.id} ${d.title}: ${d.status}. ${d.evidence||'No evidence reference.'}`).join('\n')}\n`,'text/markdown');}
function exportCalendar(){const clean=s=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Vectra3D//Graduation Baseline//EN','CALSCALE:GREGORIAN'];const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+Z/,'Z');for(const m of currentMilestones()){const i=m.index;lines.push('BEGIN:VEVENT',`UID:graduation-2026-${i}@vectra3d.local`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${m.date.replaceAll('-','')}`,`DTEND;VALUE=DATE:${addDays(m.date,1).replaceAll('-','')}`,`SUMMARY:${clean((m.changed?'EDITED / VERIFY: ':'')+(m.type==='Provisional'?'PROVISIONAL: ':'')+m.title)}`,`DESCRIPTION:${clean(m.source+'. '+m.type+'. Source date: '+m.originalDate+'. '+(m.taskId?'Linked task: '+m.taskId+'. ':'')+'Current planning export; edited dates require verification. Original review weeks and agreement date are retained.')}`,'STATUS:TENTATIVE','TRANSP:TRANSPARENT','END:VEVENT');}lines.push('END:VCALENDAR');const fold=line=>{let parts=[],part='';for(const c of line){if(new TextEncoder().encode(part+c).length>73){parts.push(part);part=' '+c;}else part+=c;}parts.push(part);return parts.join('\r\n');};download('Vectra3D-current-plan.ics',lines.map(fold).join('\r\n')+'\r\n','text/calendar');toast('Current calendar downloaded. Review provisional and edited dates before importing.');}
document.querySelector('#backup').addEventListener('click',backup);
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;
 if(el.dataset.weekOpen){taskFilter.week=el.dataset.weekOpen;taskFilter.status='all';taskFilter.search='';if(location.hash==='#tasks')render();else location.hash='tasks';}
 if(el.id==='backup-inline'||el.id==='export-unsaved')backup();if(el.id==='recovery-export'){try{const raw=localStorage.getItem(RECOVERY_KEY);if(!raw){toast('No pre-restore copy yet. One is kept before replacing a valid saved dashboard.');return;}validate(JSON.parse(raw));download('Vectra3D-before-restore-'+today+'.json',raw,'application/json');toast('Pre-restore copy downloaded. Use Restore backup to recover it.');}catch(err){toast('Recovery copy unavailable: '+err.message);}}if(el.id==='calendar')exportCalendar();if(el.id==='review-export')exportReview();if(el.id==='print-review')window.print();if(el.id==='restore')document.querySelector('#restore-file').click();
 if(el.dataset.delete){const entry=state.logs.find(x=>x.id===el.dataset.delete);if(!entry)return;state.logs=state.logs.filter(x=>x.id!==entry.id);save();render();const n=document.querySelector('#notice');n.replaceChildren(document.createTextNode('Entry removed. '));const undo=document.createElement('button');undo.textContent='Undo';undo.className='small-button';undo.onclick=()=>{if(!state.logs.some(l=>l.id===entry.id))state.logs.push(entry);save();render();n.style.display='none';};n.append(undo);n.style.display='block';clearTimeout(toast.t);}
});
document.addEventListener('input',e=>{const el=e.target;if(el.id==='task-search'){taskFilter.search=el.value;document.querySelector('#task-results').innerHTML=tasksTable(filteredTasks());}if(el.id==='review-notes'){state.review=el.value;save();}if(el.dataset.evidence){state.deliverables.find(t=>t.id===el.dataset.evidence).evidence=el.value;save();document.querySelector('#evidence-summary').textContent=evidenceSummary();}});
document.addEventListener('change',e=>{const el=e.target;
 if(el.id==='task-week'||el.id==='task-status'){taskFilter[el.id==='task-week'?'week':'status']=el.value;document.querySelector('#task-results').innerHTML=tasksTable(filteredTasks());}
 if(el.dataset.task){const id=el.dataset.task;state.tasks.find(t=>t.id===id).status=el.value;save();if(location.hash==='#tasks'){document.querySelector('#task-results').innerHTML=tasksTable(filteredTasks());(document.querySelector(`[data-task="${id}"]`)||document.querySelector('#task-status')).focus();}}
 if(el.dataset.date){const t=state.tasks.find(t=>t.id===el.dataset.date);if(!validDate(el.value)){el.value=t.due;toast('Enter a valid due date.');return;}t.due=el.value;save();el.closest('tr').cells[2].innerHTML=fmt(t.due)+(t.due<today&&t.status!=='Done'?'<p class="danger">Past plan date · verify</p>':'');}
 if(el.dataset.deliverable){state.deliverables.find(t=>t.id===el.dataset.deliverable).status=el.value;save();document.querySelector('#evidence-summary').textContent=evidenceSummary();}
  if(el.dataset.risk){state.risks.find(t=>t.id===el.dataset.risk).status=el.value;save();}
 if(el.dataset.study){const r=state.research.find(r=>r.id===el.dataset.study),v=Number(el.value);if(el.value===''||!Number.isInteger(v)||v<0||v>10000){el.value=r[el.dataset.field];toast('Enter a whole count from 0 to 10,000.');return;}r[el.dataset.field]=v;save();}
 if(el.id==='log-type'){const v=document.querySelector('#log-value'),hours=['Graduation','Business'].includes(el.value),expense=el.value==='Expense';document.querySelector('#value-label').firstChild.textContent=hours?'Hours':expense?'Amount (€)':'No amount needed';v.disabled=!hours&&!expense;v.required=hours||expense;v.max=hours?'24':'100000';v.min=hours?'0.25':'0.01';v.step=hours?'0.25':'0.01';v.value='';}
});
document.addEventListener('submit',e=>{if(e.target.id!=='log-form')return;e.preventDefault();const fd=new FormData(e.target),type=fd.get('type'),date=fd.get('date'),note=String(fd.get('note')).trim(),value=Number(fd.get('value')||0);if(!validDate(date)||!note||!Number.isFinite(value)||value<0||(['Graduation','Business'].includes(type)&&value>24))return toast('Check the date, amount and note.');if(['Graduation','Business'].includes(type)){const daily=state.logs.filter(l=>l.date===date&&['Graduation','Business'].includes(l.type)).reduce((s,l)=>s+l.value,0);if(daily+value>24)return toast('The combined hours for this date would exceed 24. Check existing entries.');}state.logs.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date,type,value,note});const saved=save();render();if(saved)toast('Entry saved.');});
document.querySelector('#restore-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10000000)throw Error('The file is too large. Choose a dashboard JSON backup under 10 MB.');restoreCandidate=validate(JSON.parse(await f.text()));document.querySelector('#restore-summary').textContent=`${restoreCandidate.tasks.filter(t=>t.status==='Done').length} completed tasks, ${restoreCandidate.logs.length} log entries. Only editable data will be restored; source requirements stay intact.`;document.querySelector('#restore-dialog').showModal();}catch(err){toast('Restore stopped: '+err.message);}e.target.value='';});
document.querySelector('#cancel-restore').onclick=()=>{restoreCandidate=null;document.querySelector('#restore-dialog').close();};
document.querySelector('#confirm-restore').onclick=()=>{if(!restoreCandidate)return;try{const previous=localStorage.getItem(KEY);if(previous){try{validate(JSON.parse(previous));localStorage.setItem(RECOVERY_KEY,previous);}catch(err){if(err.name==='QuotaExceededError'||err.name==='SecurityError')throw err;}}const raw=JSON.stringify(restoreCandidate);localStorage.setItem(KEY,raw);lastSavedRaw=raw;state=restoreCandidate;storageOK=true;restoreCandidate=null;document.querySelector('#restore-dialog').close();save();render();toast('Backup restored.');}catch(err){toast('Restore could not save to this browser. Current entries were kept.');}};
window.addEventListener('hashchange',()=>{render();document.querySelector('#main').focus();window.scrollTo(0,0);});
window.addEventListener('storage',e=>{if(e.key===KEY||e.key===null){storageOK=false;storageWarning('Another tab changed or cleared this dashboard. Export your edits before reloading; automatic saving is paused.');}});
render();if(initialWarning){storageWarning(initialWarning);toast(initialWarning);}else document.querySelector('#save-state').textContent='Local storage · export regularly';

window.addEventListener('beforeunload',e=>{if(!storageOK||document.querySelector('#save-state').textContent.startsWith('Not saved')){e.preventDefault();e.returnValue='';}});
